Repository ps2alerts/aggregator, pull requests merged in 2020-08, with the labels that each got.

#104 Implemented Kernel termination code for services
  src/bootstrap/Kernel.ts
  src/index.ts
  src/interfaces/ServiceInterface.ts
  src/logger/DiscordTransport.ts
  src/services/census/CensusStreamService.ts
  src/services/subscribers/CensusEventSubscriberService.ts
Labels: bug, p1

#105 #70 - Population Tracking
  src/authorities/PopulationAuthority.ts
  src/authorities/index.ts
  src/config/census.ts
  src/constants/types.ts
  src/data/CharacterData.ts
  src/data/InstancePopulationData.ts
  src/data/PopulationData.ts
  src/handlers/CharacterPresenceHandler.ts
  src/handlers/InstanceHandler.ts
  src/handlers/PlayerHandler.ts
  src/handlers/PopulationHandler.ts
  src/handlers/aggregate/index.ts
  src/handlers/aggregate/instance/InstancePopulationAggregate.ts
  src/handlers/census/AchievementEarnedHandler.ts
  src/handlers/census/BattleRankUpHandler.ts
  src/handlers/census/DeathEventHandler.ts
  src/handlers/census/FacilityControlEventHandler.ts
  src/handlers/census/GainExperienceEventHandler.ts
  src/handlers/census/PlayerFacilityCaptureHandler.ts
  src/handlers/census/PlayerFacilityDefendHandler.ts
  src/handlers/census/PlayerLoginEventHandler.ts
  src/handlers/census/PlayerLogoutEventHandler.ts
  src/handlers/index.ts
  src/interfaces/CharacterPresenceHandlerInterface.ts
  src/interfaces/PlayerHandlerInterface.ts
  src/interfaces/PopulationHandlerInterface.ts
  src/models/CharacterPresenceModel.ts
  src/models/aggregate/instance/InstancePopulationAggregateModel.ts
  src/services/census/CensusStreamService.ts
  src/services/mongo/index.ts
  src/services/subscribers/CensusEventSubscriberService.ts
Labels: enhancement

#118 Bump ps2census v0.4.2
  package-lock.json
  package.json
  src/handlers/aggregate/global/GlobalClassAggregate.ts
  src/handlers/aggregate/global/GlobalFactionCombatAggregate.ts
  src/handlers/aggregate/global/GlobalPlayerAggregate.ts
  src/handlers/aggregate/global/GlobalWeaponAggregate.ts
  src/handlers/aggregate/instance/InstanceClassAggregate.ts
  src/handlers/aggregate/instance/InstanceFactionCombatAggregate.ts
  src/handlers/aggregate/instance/InstancePlayerAggregate.ts
  src/handlers/aggregate/instance/InstanceWeaponAggregate.ts
  src/handlers/census/DeathEventHandler.ts
  src/handlers/census/events/DeathEvent.ts
Labels: bug, enhancement
