Repository ps2alerts/aggregator, pull requests merged in 2020-07, with the labels that each got.

#23 feat: EventMessage Handlers
  app/.eslintignore
  app/src/bootstrap.ts
  app/src/config/app.ts
  app/src/config/logger.ts
  app/src/constants/faction.ts
  app/src/constants/types.ts
  app/src/constants/zone.ts
  app/src/exceptions/ApplicationException.ts
  app/src/exceptions/IllegalArgumentException.ts
  app/src/handlers/AlertHandler.ts
  app/src/handlers/PlayerHandler.ts
  app/src/handlers/census/CensusProxy.ts
  app/src/handlers/census/ContinentLockHandler.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/handlers/census/MetagameEventEventHandler.ts
  app/src/handlers/census/PlayerLoginEventHandler.ts
  app/src/handlers/census/PlayerLogoutEventHandler.ts
  app/src/handlers/census/events/ContinentLockEvent.ts
  app/src/handlers/census/events/DeathEvent.ts
  app/src/handlers/census/events/FacilityControlEvent.ts
  app/src/handlers/census/events/MetagameEventEvent.ts
  app/src/handlers/census/events/PlayerLoginEvent.ts
  app/src/handlers/census/events/PlayerLogoutEvent.ts
  app/src/handlers/index.ts
  app/src/interfaces/AlertHandlerInterface.ts
  app/src/interfaces/PlayerHandlerInterface.ts
  app/src/utils/FactionUtils.ts
  app/src/utils/ZoneUtils.ts
  app/src/utils/eventId.ts
  app/src/utils/parser.ts
Labels: enhancement, p1

#35 feat: Additional EventMessage Handlers
  app/src/exceptions/IllegalArgumentException.ts
  app/src/handlers/PlayerHandler.ts
  app/src/handlers/census/AchievementEarnedHandler.ts
  app/src/handlers/census/BattleRankUpHandler.ts
  app/src/handlers/census/CensusProxy.ts
  app/src/handlers/census/ContinentLockHandler.ts
  app/src/handlers/census/ContinentUnlockHandler.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/handlers/census/GainExperienceHandler.ts
  app/src/handlers/census/MetagameEventEventHandler.ts
  app/src/handlers/census/PlayerFacilityCaptureHandler.ts
  app/src/handlers/census/PlayerFacilityDefendHandler.ts
  app/src/handlers/census/PlayerLoginEventHandler.ts
  app/src/handlers/census/PlayerLogoutEventHandler.ts
  app/src/handlers/census/events/AchievementEarnedEvent.ts
  app/src/handlers/census/events/BattleRankUpEvent.ts
  app/src/handlers/census/events/ContinentLockEvent.ts
  app/src/handlers/census/events/ContinentUnlockEvent.ts
  app/src/handlers/census/events/DeathEvent.ts
  app/src/handlers/census/events/FacilityControlEvent.ts
  app/src/handlers/census/events/GainExperienceEvent.ts
  app/src/handlers/census/events/MetagameEventEvent.ts
  app/src/handlers/census/events/PlayerFacilityCaptureEvent.ts
  app/src/handlers/census/events/PlayerFacilityDefendEvent.ts
  app/src/handlers/census/events/PlayerLoginEvent.ts
  app/src/handlers/census/events/PlayerLogoutEvent.ts
  app/src/interfaces/PlayerHandlerInterface.ts
  app/src/utils/FactionUtils.ts
  app/src/utils/ZoneUtils.ts
  app/src/utils/parser.ts
Labels: enhancement, p1

#40 fix: Update ps2census to 0.2.4
  app/package-lock.json
  app/package.json
  app/src/handlers/census/AchievementEarnedHandler.ts
  app/src/handlers/census/BattleRankUpHandler.ts
  app/src/handlers/census/CensusProxy.ts
  app/src/handlers/census/ContinentLockEventHandler.ts
  app/src/handlers/census/ContinentUnlockHandler.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/handlers/census/GainExperienceEventHandler.ts
  app/src/handlers/census/MetagameEventEventHandler.ts
  app/src/handlers/census/PlayerFacilityCaptureHandler.ts
  app/src/handlers/census/PlayerFacilityDefendHandler.ts
  app/src/handlers/census/PlayerLoginEventHandler.ts
  app/src/handlers/census/PlayerLogoutEventHandler.ts
  app/src/handlers/census/events/AchievementEarnedEvent.ts
  app/src/handlers/census/events/BattleRankUpEvent.ts
  app/src/handlers/census/events/ContinentLockEvent.ts
  app/src/handlers/census/events/ContinentUnlockEvent.ts
  app/src/handlers/census/events/DeathEvent.ts
  app/src/handlers/census/events/FacilityControlEvent.ts
  app/src/handlers/census/events/GainExperienceEvent.ts
  app/src/handlers/census/events/MetagameEventEvent.ts
  app/src/handlers/census/events/PlayerFacilityCaptureEvent.ts
  app/src/handlers/census/events/PlayerFacilityDefendEvent.ts
  app/src/handlers/census/events/PlayerLoginEvent.ts
  app/src/handlers/census/events/PlayerLogoutEvent.ts
  app/src/interfaces/EventHandlerInterface.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/census/index.ts
  app/src/utils/json.ts
Labels: enhancement

#50 Fix statics within MongoDBConnection
  app/src/services/mongo/MongoDBConnection.ts
  app/src/services/mongo/index.ts
Labels: enhancement

#51 Fix MongoDBConnection
  app/src/services/mongo/MongoDBConnection.ts
Labels: bug

#53 Potential fix issue #52
  app/src/services/census/CensusStreamService.ts
Labels: bug

#55 Created Mongoose connection and implemented MetagameEvent handler
  .gitignore
  app/package-lock.json
  app/package.json
  app/src/bootstrap/Kernel.ts
  app/src/config/census.ts
  app/src/config/database.ts
  app/src/constants/facilityType.ts
  app/src/constants/loadout.ts
  app/src/constants/metagameEventState.ts
  app/src/constants/playerFacility.ts
  app/src/constants/playerPresenceStates.ts
  app/src/constants/types.ts
  app/src/constants/vehicle.ts
  app/src/constants/world.ts
  app/src/constants/zone.ts
  app/src/factories/MongooseModelFactory.ts
  app/src/handlers/AlertHandler.ts
  app/src/handlers/PlayerHandler.ts
  app/src/handlers/census/AchievementEarnedHandler.ts
  app/src/handlers/census/BattleRankUpHandler.ts
  app/src/handlers/census/CensusProxy.ts
  app/src/handlers/census/ContinentLockEventHandler.ts
  app/src/handlers/census/ContinentUnlockHandler.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/handlers/census/GainExperienceEventHandler.ts
  app/src/handlers/census/MetagameEventEventHandler.ts
  app/src/handlers/census/PlayerFacilityCaptureHandler.ts
  app/src/handlers/census/PlayerFacilityDefendHandler.ts
  app/src/handlers/census/PlayerLoginEventHandler.ts
  app/src/handlers/census/PlayerLogoutEventHandler.ts
  app/src/handlers/census/events/MetagameEventEvent.ts
  app/src/interfaces/AlertHandlerInterface.ts
  app/src/interfaces/CensusEvents.ts
  app/src/interfaces/EventHandlerInterface.ts
  app/src/interfaces/PlayerHandlerInterface.ts
  app/src/models/AlertDeathModel.ts
  app/src/models/AlertModel.ts
  app/src/models/static/PlayerModel.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/census/index.ts
  app/src/services/mongo/MongoDBConnection.ts
  app/src/services/mongo/index.ts
  app/src/types/censusStreaming.ts
  app/src/utils/alert.ts
  app/src/utils/eventId.ts
  app/src/utils/time.ts
  provisioning/dev/start-full.yml
  provisioning/dev/start.yml
Labels: enhancement, p1

#57 Implemented Death event and introduced ActiveAlertAuthority
  app/src/authorities/ActiveAlertAuthority.ts
  app/src/authorities/index.ts
  app/src/config/app.ts
  app/src/config/features.ts
  app/src/constants/faction.ts
  app/src/constants/loadout.ts
  app/src/constants/types.ts
  app/src/handlers/AlertHandler.ts
  app/src/handlers/PlayerHandler.ts
  app/src/handlers/census/AchievementEarnedHandler.ts
  app/src/handlers/census/BattleRankUpHandler.ts
  app/src/handlers/census/CensusProxy.ts
  app/src/handlers/census/ContinentLockEventHandler.ts
  app/src/handlers/census/ContinentUnlockHandler.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/handlers/census/GainExperienceEventHandler.ts
  app/src/handlers/census/MetagameEventEventHandler.ts
  app/src/handlers/census/PlayerFacilityCaptureHandler.ts
  app/src/handlers/census/PlayerFacilityDefendHandler.ts
  app/src/handlers/census/PlayerLoginEventHandler.ts
  app/src/handlers/census/PlayerLogoutEventHandler.ts
  app/src/handlers/census/events/AchievementEarnedEvent.ts
  app/src/handlers/census/events/BattleRankUpEvent.ts
  app/src/handlers/census/events/ContinentLockEvent.ts
  app/src/handlers/census/events/ContinentUnlockEvent.ts
  app/src/handlers/census/events/DeathEvent.ts
  app/src/handlers/census/events/FacilityControlEvent.ts
  app/src/handlers/census/events/GainExperienceEvent.ts
  app/src/handlers/census/events/MetagameEventEvent.ts
  app/src/handlers/census/events/PlayerFacilityCaptureEvent.ts
  app/src/handlers/census/events/PlayerFacilityDefendEvent.ts
  app/src/handlers/census/events/PlayerLoginEvent.ts
  app/src/handlers/census/events/PlayerLogoutEvent.ts
  app/src/handlers/index.ts
  app/src/interfaces/ActiveAlertAuthorityInterface.ts
  app/src/interfaces/ActiveAlertInterface.ts
  app/src/interfaces/EventHandlerInterface.ts
  app/src/interfaces/PlayerHandlerInterface.ts
  app/src/models/ActiveAlertModel.ts
  app/src/models/AlertDeathModel.ts
  app/src/models/AlertModel.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/mongo/MongoDatabaseConnectionService.ts
  app/src/services/mongo/index.ts
  app/src/services/subscribers/CensusEventSubscriberService.ts
  app/src/services/subscribers/index.ts
  app/src/types/PS2AlertsEvent.ts
  app/src/utils/FactionUtils.ts
  app/src/utils/alert.ts
  app/src/utils/parser.ts
Labels: enhancement, p1

#58 #26 - Implemented AlertFactionCombatAggregate
  app/src/bootstrap/Kernel.ts
  app/src/config/app.ts
  app/src/config/census.ts
  app/src/constants/metagameEventIds.ts
  app/src/constants/types.ts
  app/src/handlers/aggregate/alert/AlertFactionCombatAggregate.ts
  app/src/handlers/aggregate/index.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/events/DeathEvent.ts
  app/src/interfaces/AggregateHandlerInterface.ts
  app/src/models/aggregate/AlertFactionCombatAggregateModel.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/mongo/index.ts
  app/src/utils/FactionUtils.ts
Labels: enhancement, p1

#59 #45 - FacilityControl event implementation
  app/src/config/census.ts
  app/src/config/features.ts
  app/src/constants/types.ts
  app/src/handlers/census/DeathEventHandler.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/handlers/census/events/FacilityControlEvent.ts
  app/src/models/AlertFacilityControlModel.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/mongo/index.ts
  app/src/services/subscribers/CensusEventSubscriberService.ts
Labels: enhancement, p1

#60 #26 - AlertFacilityControlAggregate
  app/src/constants/types.ts
  app/src/handlers/aggregate/alert/AlertFacilityControlAggregate.ts
  app/src/handlers/aggregate/index.ts
  app/src/handlers/census/FacilityControlEventHandler.ts
  app/src/models/aggregate/AlertFacilityControlAggregateModel.ts
  app/src/services/mongo/index.ts
Labels: enhancement, p1

#65 #26 - AlertPlayerAggregate & GlobalPlayerAggregate
  app/src/constants/types.ts
  app/src/handlers/aggregate/alert/AlertPlayerAggregate.ts
  app/src/handlers/aggregate/global/GlobalPlayerAggregate.ts
  app/src/handlers/aggregate/index.ts
  app/src/interfaces/AggregateHandlerInterface.ts
  app/src/models/aggregate/AlertPlayerAggregateModel.ts
  app/src/models/aggregate/GlobalPlayerAggregateModel.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/mongo/index.ts
Labels: enhancement, p1

#66 #26 - AlertWeaponAggregate & GlobalWeaponAggregate
  app/src/constants/types.ts
  app/src/handlers/aggregate/alert/AlertWeaponAggregate.ts
  app/src/handlers/aggregate/global/GlobalWeaponAggregate.ts
  app/src/handlers/aggregate/index.ts
  app/src/models/aggregate/AlertWeaponAggregateModel.ts
  app/src/models/aggregate/GlobalWeaponAggregateModel.ts
  app/src/services/mongo/index.ts
Labels: enhancement, p1

#74 Revive branch, staging environment and various bugfixes
  .github/workflows/deploy-staging.yml
  app/package.json
  app/src/bootstrap/Kernel.ts
  app/src/config/app.ts
  app/src/config/census.ts
  app/src/config/database.ts
  app/src/config/logger.ts
  app/src/handlers/AlertHandler.ts
  app/src/handlers/aggregate/alert/AlertClassAggregate.ts
  app/src/handlers/aggregate/alert/AlertFacilityControlAggregate.ts
  app/src/handlers/aggregate/alert/AlertFactionCombatAggregate.ts
  app/src/handlers/aggregate/alert/AlertPlayerAggregate.ts
  app/src/handlers/aggregate/alert/AlertWeaponAggregate.ts
  app/src/handlers/aggregate/global/GlobalClassAggregate.ts
  app/src/handlers/aggregate/global/GlobalPlayerAggregate.ts
  app/src/handlers/aggregate/global/GlobalWeaponAggregate.ts
  app/src/handlers/census/MetagameEventEventHandler.ts
  app/src/models/aggregate/alert/AlertClassAggregateModel.ts
  app/src/models/aggregate/alert/AlertPlayerAggregateModel.ts
  app/src/models/aggregate/alert/AlertWeaponAggregateModel.ts
  app/src/models/aggregate/global/GlobalClassAggregateModel.ts
  app/src/models/aggregate/global/GlobalPlayerAggregateModel.ts
  app/src/models/aggregate/global/GlobalWeaponAggregateModel.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/census/index.ts
  app/tsconfig.json
  provisioning/dev/start-full.yml
  provisioning/staging/Dockerfile
  provisioning/staging/files/entrypoint.sh
  provisioning/staging/k8s/manifests/cluster-issuer.yml
  provisioning/terraform/.gitignore
  provisioning/terraform/main.tf
  provisioning/terraform/modules/websocket/main.tf
  provisioning/terraform/modules/websocket/variables.tf
  provisioning/terraform/staging.tf
  provisioning/terraform/variables.tf
Labels: enhancement, p1

#79 Feature/priority boot sequence
  app/src/bootstrap/Kernel.ts
  app/src/interfaces/ServiceInterface.ts
  app/src/services/census/CensusStreamService.ts
  app/src/services/mongo/MongoDatabaseConnectionService.ts
  app/src/services/subscribers/CensusEventSubscriberService.ts
Labels: enhancement

#83 Feature/63 upgrade ps2census
  app/package-lock.json
  app/package.json
  app/src/handlers/census/events/AchievementEarnedEvent.ts
  app/src/handlers/census/events/BattleRankUpEvent.ts
  app/src/handlers/census/events/ContinentLockEvent.ts
  app/src/handlers/census/events/ContinentUnlockEvent.ts
  app/src/handlers/census/events/DeathEvent.ts
  app/src/handlers/census/events/FacilityControlEvent.ts
  app/src/handlers/census/events/GainExperienceEvent.ts
  app/src/handlers/census/events/MetagameEventEvent.ts
  app/src/handlers/census/events/PlayerFacilityCaptureEvent.ts
  app/src/handlers/census/events/PlayerFacilityDefendEvent.ts
  app/src/handlers/census/events/PlayerLoginEvent.ts
  app/src/handlers/census/events/PlayerLogoutEvent.ts
  app/src/models/InstanceDeathModel.ts
  app/src/models/InstanceFacilityControlModel.ts
  app/src/models/InstanceModel.ts
  app/src/services/subscribers/CensusEventSubscriberService.ts
  app/src/utils/parser.ts
Labels: enhancement

#85 Fixy fix
  app/src/handlers/InstanceHandler.ts
Labels: bug

#89 Implemented a queue for the DiscordTransport
  app/src/logger/DiscordTransport.ts
Labels: bug

#82 #80 - Census dropped connection checking
  app/package-lock.json
  app/src/services/census/CensusStreamService.ts
Labels: bug, p1

#97 Fix/69 facility control fix
  .eslintrc.js
  src/constants/faction.ts
Labels: bug
